### PR TITLE
Fix #488

### LINKED ISSUE #488: Remove 'org.springframework.boot.loader.nio.file.NestedFileSystemProvider' for Spring Boot 3.2+ native image Applications
this is a copy of https://github.com/paketo-buildpacks/native-image/issues/321

I believe it's more appropriate to handle this issue from `spring-boot` code base

## Issue
As explained on [StackOverflow](https://stackoverflow.com/a/78479911/24069), or also in the [original issue on Github](https://github.com/paketo-buildpacks/native-image/issues/321), the user could be unable to create a Spring Boot 3.2+ native application with such an error during GraalVM `native-image` step 2/8 :

```
[INFO]     [creator]     Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: An object of type 'org.springframework.boot.loader.nio.file.NestedFileSystemProvider' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
[INFO]     [creator]     This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.
[INFO]     [creator]     
[INFO]     [creator]     You now have two options to resolve this:
[INFO]     [creator]     
[INFO]     [creator]     1) If it is intended that objects of type 'org.springframework.boot.loader.nio.file.NestedFileSystemProvider' are persisted in the image heap, add 
[INFO]     [creator]     
[INFO]     [creator]         '--initialize-at-build-time=org.springframework.boot.loader.nio.file.NestedFileSystemProvider'
[INFO]     [creator]     
[INFO]     [creator]     to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'org.springframework.boot.loader.nio.file.NestedFileSystemProvider' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.
[INFO]     [creator]     
[INFO]     [creator]     2) If these objects should not be stored in the image heap, you can use 
[INFO]     [creator]     
[INFO]     [creator]         '--trace-object-instantiation=org.springframework.boot.loader.nio.file.NestedFileSystemProvider'
[INFO]     [creator]     
[INFO]     [creator]     to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 
[INFO]     [creator]     
[INFO]     [creator]         '--initialize-at-run-time=<culprit>'
[INFO]     [creator]     
[INFO]     [creator]     to prevent the instantiation of the object.
[INFO]     [creator]     
[INFO]     [creator]     If you are seeing this message after upgrading to a new GraalVM release, this means that some objects ended up in the image heap without their type being marked with --initialize-at-build-time.
[INFO]     [creator]     To fix this, include '--initialize-at-build-time=org.springframework.boot.loader.nio.file.NestedFileSystemProvider' in your configuration. If the classes do not originate from your code, it is advised to update all library or framework dependencies to the latest version before addressing this error.
[INFO]     [creator]     
[INFO]     [creator]     The following detailed trace displays from which field in the code the object was reached.
[INFO]     [creator]     Object was reached by
[INFO]     [creator]       manually created constant
[INFO]     [creator]     --------------------------------------------------------------------------------
[INFO]     [creator]         6.1s (9.6% of total time) in 130 GCs | Peak RSS: 1.21GB | CPU load: 6.54
[INFO]     [creator]     ================================================================================
[INFO]     [creator]     Failed generating 'com.example.demo.DemoApplication' after 1m 1s.
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to contribute native-image layer
[INFO]     [creator]     error running build
[INFO]     [creator]     exit status 1
[INFO]     [creator]     ERROR: failed to build: exit status 1
```

## Workaround

As @scottfrederick suggested, just set this environment variable for `native-image` buildpack to pick up.

Maven:
```
<BP_NATIVE_IMAGE_BUILD_ARGUMENTS>-H:-AddAllFileSystemProviders</BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
```

Using Pack CLI

```
--env BP_NATIVE_IMAGE_BUILD_ARGUMENTS="-H:-AddAllFileSystemProviders"
```

## Suggested  Solution

When `spring-boot` buildpack has detected the user wanted a `native-image`, from an application using SB 3.2+, remove the line containing "org.springframework.boot.loader.nio.file.NestedFileSystemProvider" from the file named "META-INF/services/java.nio.file.spi.FileSystemProvider" - if it's the only line of the file, remove the whole file

### PR DESCRIPTION
**Pull request by anthonydahanne**
* if app Spring Boot >= 3.20 and has a META-INF/services/java.nio.file.spi.FileSystemProvider file, remove the line org.springframework.boot.loader.nio.file.NestedFileSystemProvider or delete the file if it was the only line found

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

File: boot/build.go [hunk 1]
```diff
@@ -281,6 +291,43 @@ func (b Build) Build(context libcnb.BuildContext) (libcnb.BuildResult, error) {
...
+		if len(newLines) > 0 {
+			err = os.WriteFile(fileSystemProvider, []byte(strings.Join(newLines, "\n")), 0644)
+			if err != nil {
+				return fmt.Errorf("unable to write to %s\n%w", fileSystemProvider, err)
+			}
+		} else {
+			err = os.Remove(fileSystemProvider)
+			if err != nil {
+				return fmt.Errorf("unable to delete file %s\n%w", fileSystemProvider, err)
+			}
```
Comment (dmikusa) [inline boot/build.go:324]: This really isn't a big deal because this is not a performance-critical section, but you can avoid converting to strings here since the parsing/manipulation you're doing is simple. The `bytes` package has similar methods for `Split`, `Contains` and `Join`, so you could use those instead and operate directly on the bytes.

https://pkg.go.dev/bytes

**Review by dmikusa — APPROVED** [review]
Looks good. Just that one minor FYI.

File: boot/build.go (hunk 1 above)
Comment (anthonydahanne) [reply boot/build.go]: okee dok! done! thanks!

**Review by dmikusa — APPROVED** [review]
