### PR TITLE
correctly handles case where no jar was found

### LINKED ISSUE #474: Broken detection logic on non-spring projects
## Expected Behavior

The buildpack should not kick in for non Spring-Boot apps.

## Current Behavior

Building the [war](https://github.com/paketo-buildpacks/samples/tree/main/java/war) sample using 

```
pack build --clear-cache --builder paketobuildpacks/builder-jammy-base --env BP_JVM_VERSION=11 --buildpack gcr.io/paketo-buildpacks/java:13.0.0 sample-war
```

currently fails with 

```
Paketo Buildpack for Spring Boot 5.29.0
  unable to find Spring Boot Executable Jar
  open : no such file or directory
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

## Possible Solution

The [logic](https://github.com/paketo-buildpacks/spring-boot/blob/f842af4a21c9b8acd26979cba6e834776d6d6a5a/boot/build.go#L69-L80) seems to be complicated and probably needs an [early return](https://github.com/paketo-buildpacks/spring-boot/blob/7944296ccb7ecefd2ef5da13cd83f48269ea60ff/boot/build.go#L59-L63) if the app is not using spring-boot.

## Steps to Reproduce

1. Clone samples
2. Run `pack build` using the latest release

### PR DESCRIPTION
**Pull request by pivotal-david-osullivan**
## Summary
Fixes #474 

## Use Cases
Walking the application path to find a non-exploded jar did not handle finding no suitable jar correctly - this fix ensures that 
either no jar being found, or a non-boot jar being found, results in the expected backing off of the Boot buildpack during build.

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

File: boot/build_test.go [hunk 1]
```diff
@@ -637,4 +629,45 @@ Spring-Boot-Lib: BOOT-INF/lib
...
+	context("when there is a non-exploded jar passed to the buildpack", func() {
+
+		it.Before(func() {
+			t.Setenv("BP_SPRING_CLOUD_BINDINGS_DISABLED", "true")
+			os.Remove(filepath.Join(ctx.Application.Path, "META-INF"))
+		})
+
+		it("finds and extracts a jar that exists", func(){
+
+	    	Copy("cds","spring-app-3.3-no-dependencies.jar", "")
```
Comment (anthonydahanne) [inline boot/build_test.go:642]:
```suggestion
			Copy("cds","spring-app-3.3-no-dependencies.jar", "")
```

should be indented like the line below (Expect); with 3 tabs

**Review by anthonydahanne — APPROVED** [review]
